import '../styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '../../components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'G William Boyd | Full Stack Web Developer',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	/* let scrolled: boolean
	document.addEventListener('scroll', () => {
		window.scrollY > 0 ? (scrolled = true) : (scrolled = false)
		console.log(scrolled)
	}) */
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Navbar />
				{children}
			</body>
		</html>
	)
}
