import '../styles/globals.css'
import type { Metadata } from 'next'
import { Jost } from 'next/font/google'
import Navbar from '../../components/Navbar'

const jost = Jost({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'G William Boyd | Full-Stack Web Developer',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={jost.className}>
				<Navbar />
				{children}
			</body>
		</html>
	)
}
